version: '3.8'

# Override para desenvolvimento com hot-reload
services:
  api:
    volumes:
      - ./app:/app/app:rw  # Read-write para hot-reload
      - ./logs:/logs
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=true
    command: >
      bash -c "
        cd /app &&
        python /app/init_admin.py &&
        uvicorn app.main:app --host 0.0.0.0 --port 8430 --reload
      "

  streamlit:
    volumes:
      - ./app:/app/app:rw  # Read-write para hot-reload
      - ./logs:/logs
    environment:
      - PYTHONUNBUFFERED=1
      - DEBUG=true

  # Container para desenvolvimento/debug
  debug:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: cnpj_debug
    depends_on:
      - db
    environment:
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: cnpj_rede
    volumes:
      - ./app:/app/app:rw
      - ./database/scripts:/scripts:rw
      - dados_publicos:/dados-publicos
      - dados_zip:/dados-publicos-zip
    networks:
      - cnpj_network
    command: tail -f /dev/null  # Mantém container rodando